[package]
name = "pi_ui_render"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
default = ["pi_js_export"]
pi_js_export = []

[dependencies]
pi_print_any= "0.1"
pi_slotmap = "0.1"
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "1.4"
derive_deref = "1.1"
paste = "0.1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"], option=true }
ordered-float = { version = "3.0", default-features = false, features = ["serde"] }
fxhash = "0.2.1"
nalgebra = {version = "0.30", features = ["serde", "serde-serialize"]}
ncollide2d = {version = "0.33", features = ["serde"]}
log="0.4"
smallvec={version = "1.8", features = ["serde"]}
getset="0.1"
bitvec={version = "1.0", features = ["serde"]}
cssparser = "0.29"
pi_hash="0.1" 
pi_atom={version="0.2", features = ["serde"]}
pi_enum_default_macro="0.1"
pi_res="0.1"
pi_map="0.1"
pi_null="0.1"
pi_ucd="0.1"
pi_data_view = "0.1"
futures = "0.3"
pi_polygon = "0.1"
pi_cg2d = "0.2"
crossbeam="0.8"
pi_graph = "0.1"
fixedbitset = {version="0.4", features = ["serde"]}
bytemuck = { version = "1.4", features = ["derive"] }
naga = { version = "0.9", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
pi_assets = "0.10"
image = "0.24"
polygon2 = "0.3"
json ="0.12"
pi_slab="0.1"
pi_idtree="0.1"
pi_slotmap_tree ="0.3"
pi_dirty="0.1"

pi_spatialtree = { git = "https://github.com/GaiaWorld/pi_spatialtree.git" }
pi_ecs_macros = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
# pi_ecs_utils = { git = "https://github.com/GaiaWorld/pi_ecs_utils.git" }
pi_ecs_utils = {path="../pi_ecs_utils"}
pi_ecs = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
pi_flex_layout = { git = "https://github.com/GaiaWorld/pi_flex_layout.git" }
pi_hal={git="https://github.com/GaiaWorld/pi_hal.git"}
js_proxy_gen_macro={git="https://github.com/GaiaWorld/pi_lib.git"}
pi_postprocess={git="https://github.com/GaiaWorld/pi_post_process.git"}
pi_curves = { git="https://github.com/GaiaWorld/pi_curves.git"}
pi_animation = {git="https://github.com/GaiaWorld/pi_animation.git"}
render_derive = {git="https://github.com/GaiaWorld/pi_render.git"}
pi_style = {path="../pi_style"}
pi_futures="0.1"
pi_time="0.2"
siphasher = {version="0.3", features=["serde_no_std"]}
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
bevy="0.9"
winit = {git = "http://ser.yinengyun.com:10082/tech/winit.git"}

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
uuid = { version = "1", features = ["js"] }
pi_share = {version="0.4", features=["serial", "rc"]}
pi_async = {version = "0.5", features = ["serial"]}
web-sys = {version="0.3", features = [
	"HtmlCanvasElement"
]}
js-sys = "0.3"
wgpu = { version = "0.13", features = ["spirv", "glsl", "webgl"] }
pi_render = { git = "https://github.com/GaiaWorld/pi_render.git", features=["webgl"] }
flume = {version="0.10", features=["spin"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pi_share = {version="0.4"}
pi_async = "0.5"
wgpu = { version = "0.13", features = ["spirv", "glsl"] }
pi_render = { git = "https://github.com/GaiaWorld/pi_render.git"}
flume = "0.10"


# [patch."https://github.com/GaiaWorld/pi_spatialtree"]
# pi_spatialtree ={path="../pi_spatialtree"}

# [patch."https://github.com/GaiaWorld/pi_post_process"]
# pi_postprocess ={path="../pi_post_process"}

# [patch."https://github.com/GaiaWorld/pi_curves"]
# pi_curves  = {path="../pi_curves"}

# [patch."https://github.com/GaiaWorld/pi_animation"]
# pi_animation = { path="../pi_animation"}

# [patch."https://github.com/GaiaWorld/pi_ecs"]
# pi_ecs = { path = "../pi_ecs" }
# pi_ecs_macros = { path = "../pi_ecs/macros" }


# [patch."https://github.com/GaiaWorld/pi_ecs_utils"]
# pi_ecs_utils = { path = "../pi_ecs_utils" }

# [patch."https://github.com/GaiaWorld/pi_render"]
# pi_render = { path = "../pi_render" }
# render_derive = {path = "../pi_render/crates/render_derive"}

# [patch."https://github.com/GaiaWorld/pi_hal"]
# pi_hal = { path = "../pi_hal" }

[patch."https://github.com/GaiaWorld/pi_flex_layout"]
pi_flex_layout = { path = "../pi_flex_layout" }

# [patch."http://ser.yinengyun.com:10082/tech/font_kit.git"]
# font_kit = { path = "../font_kit" }

[patch.crates-io]
# pi_slotmap_tree = { path = "../pi_slotmap_tree" }
# pi_assets = {path="../pi_assets"}
# pi_graph = {path = "../pi_graph"}
# wgpu = { path = "../wgpu1/wgpu"}
# pi_assets = {path = "../pi_assets"}
# pi_slotmap = { path = "../pi_slotmap" }

# pi_dirty = { path = "../pi_dirty" }
# wgpu = { path = "../wgpu/wgpu" }


[[example]]
name = "quad"
test = true

[dev-dependencies]
env_logger = "0.9"
float-ord = "0.3"
async-trait="0.1"
font_kit = {git="http://ser.yinengyun.com:10082/tech/font_kit.git"}
spin_sleep="1.1"
num_cpus = "1.13"

[build-dependencies]
# render_compile = { git = "https://github.com/GaiaWorld/pi_render.git" }
render_compile = {path="../pi_render/crates/render_compile"}
naga = { version = "0.9", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }


# [patch.crates-io]
# pi_ecs = { path = "../pi_ecs" }
# pi_ecs_macros = { path = "../pi_ecs/macros" }
# pi_flex_layout = { path = "../pi_flex_layout" }
# pi_slotmap_tree = { path = "../pi_slotmap_tree" }
# pi_dirty = { path = "../pi_dirty" }


# tree = { path = "../pi_lib/tree"}
# slotmap = { path = "../pi_lib/slotmap"}
# slab = {path="../pi_lib/slab"}
# atom = {path="../pi_lib/atom"}
# map = {path="../pi_lib/map"}
# any = {path="../pi_lib/any"}
# listener = {path="../pi_lib/listener"}
# hash = {path="../pi_lib/hash"}
# time = {path="../pi_lib/time"}
# share = {path="../pi_lib/share"}
# wy_rng = {path="../pi_lib/wy_rng"}
# debug_info = {path="../pi_lib/debug_info"}
# graph = {path="../pi_lib/graph"}
# async_graph = {path="../pi_lib/async_graph"}
# async = {path="../pi_lib/async"}
# dirty = { path= "../pi_lib/dirty"}
# pi_ecs_macros = { path = "macros"}
# paste = "0.1"
# lazy_static = "*"
# log = "*"
# rand = "*"
# thiserror = "1.0"
# futures = "0.3"
# fixedbitset = "0.4"




# im = "*"

# [dependencies.web-sys]
# version = "*"
# features = [
# 	"console",
# ]
[net]
# git-fetch-with-cli = true
# offline = true

