[package]
name = "pi_ui_render"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[features]
default = ["pi_js_export"]
pi_js_export = []

[dependencies]
pi_print_any= "0.1"
pi_slotmap = "0.1"
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "*"
derive_deref = "1.1"
paste = "0.1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"], option=true }
ordered-float = { version = "3.0", default-features = false, features = ["serde"] }
fxhash = "0.2.1"
nalgebra = {version = "0.24.0", features = ["serde", "serde-serialize"]}
ncollide2d = {version = "0.27.0", features = ["serde"]}
log="*"
smallvec={version = "1.8", features = ["serde"]}
getset="0.1"
bitvec={version = "1.0", features = ["serde"]}
pi_hash="0.1"
pi_share="0.1"
pi_atom={version="0.1", features = ["serde"]}
pi_enum_default_macro="0.1"
pi_res="0.1"
pi_map="0.1"
pi_null="0.1"
pi_ucd="0.1"
pi_data_view = "0.1"
pi_async = "0.2"
futures = "0.3"
pi_polygon = "0.1"
pi_cg2d = "0.1"
fixedbitset = {version="0.4", features = ["serde"]}
wgpu = { version = "0.12", features = ["spirv", "glsl"] }
bytemuck = { version = "1.4", features = ["derive"] }
naga = { version = "0.8", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
pi_assets = "0.7"
image = "0.23"
polygon2 = "0.3"
json ="0.12"
pi_slab="0.1"
pi_idtree="0.1"
winit = {git = "http://ser.yinengyun.com:10082/tech/winit.git"}
pi_slotmap_tree ="0.2"
pi_dirty="0.1"

pi_spatialtree = { git = "https://github.com/GaiaWorld/pi_spatialtree.git" }
pi_render = { git = "https://github.com/GaiaWorld/pi_render.git" }
pi_ecs_macros = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
pi_ecs_utils = { git = "https://github.com/GaiaWorld/pi_ecs_utils.git" }
pi_ecs = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
pi_flex_layout = { git = "https://github.com/GaiaWorld/pi_flex_layout.git" }
pi_hal={git="https://github.com/GaiaWorld/pi_hal.git"}
js_proxy_gen_macro={git="https://github.com/GaiaWorld/pi_lib.git"}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }

# [patch."https://github.com/GaiaWorld/pi_ecs"]
# pi_ecs = { path = "../pi_ecs" }
# pi_ecs_macros = { path = "../pi_ecs/macros" }


# [patch."https://github.com/GaiaWorld/pi_ecs_utils"]
# pi_ecs_utils = { path = "../pi_ecs_utils" }

# [patch."https://github.com/GaiaWorld/pi_render"]
# pi_render = { path = "../pi_render" }

# [patch."https://github.com/GaiaWorld/pi_hal"]
# pi_hal = { path = "../pi_hal" }

# [patch."https://github.com/GaiaWorld/pi_flex_layout"]
# pi_flex_layout = { path = "../pi_flex_layout" }

# [patch."http://ser.yinengyun.com:10082/tech/font_kit.git"]
# font_kit = { path = "../font_kit" }

# [patch.crates-io]
# pi_slotmap = { path = "../pi_slotmap" }
# pi_slotmap_tree = { path = "../pi_slotmap_tree" }
# pi_dirty = { path = "../pi_dirty" }
# wgpu = { path = "../wgpu/wgpu" }


[[example]]
name = "quad"
test = true

[dev-dependencies]
env_logger = "0.9"
float-ord = "0.3"
async-trait="0.1"
font_kit = {git="http://ser.yinengyun.com:10082/tech/font_kit.git"}
spin_sleep="1.1"
num_cpus = "1.13"

[build-dependencies]
render_compile = { git = "https://github.com/GaiaWorld/pi_render.git" }
naga = { version = "0.8", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }

# [patch.crates-io]
# pi_ecs = { path = "../pi_ecs" }
# pi_ecs_macros = { path = "../pi_ecs/macros" }
# pi_flex_layout = { path = "../pi_flex_layout" }
# pi_slotmap_tree = { path = "../pi_slotmap_tree" }
# pi_dirty = { path = "../pi_dirty" }


# tree = { path = "../pi_lib/tree"}
# slotmap = { path = "../pi_lib/slotmap"}
# slab = {path="../pi_lib/slab"}
# atom = {path="../pi_lib/atom"}
# map = {path="../pi_lib/map"}
# any = {path="../pi_lib/any"}
# listener = {path="../pi_lib/listener"}
# hash = {path="../pi_lib/hash"}
# time = {path="../pi_lib/time"}
# share = {path="../pi_lib/share"}
# wy_rng = {path="../pi_lib/wy_rng"}
# debug_info = {path="../pi_lib/debug_info"}
# graph = {path="../pi_lib/graph"}
# async_graph = {path="../pi_lib/async_graph"}
# async = {path="../pi_lib/async"}
# dirty = { path= "../pi_lib/dirty"}
# pi_ecs_macros = { path = "macros"}
# paste = "0.1"
# lazy_static = "*"
# log = "*"
# rand = "*"
# thiserror = "1.0"
# futures = "0.3"
# fixedbitset = "0.4"




# im = "*"

# [dependencies.web-sys]
# version = "*"
# features = [
# 	"console",
# ]
[net]
git-fetch-with-cli = true
offline = true