_$pi.define("app_c/demo/ui/show/base/overflow.vue.tpl", ["require", "exports", "module", "pi_gui/widget/direct", "pi_gui/ui/imgmap.vue"], function (require, exports, module, direct_1, imgmap_vue_1) {
    "use strict";

    exports.BW2 = void 0;
    const staticObj = [[1, 1], [0.47, 0.47, 0.47, 1], [0, 50], [[0, 10], null, null, null, null], [1, 0, 0, 1], [0, 70], [0, 80], [{
        t: "r",
        d: 45
    }]];
    class BW2 {
        constructor(widget, ctx) {
            this.w = widget;
        }
        c() {
            let t = this,
                w = t.w;
            t.n2 = direct_1.createDiv();
            direct_1.setStyle(t.n2, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n2, 1 /*height*/, staticObj[0]);
            direct_1.setStyle(t.n2, 22 /*flexWrap*/, 1);
            direct_1.extendAttr(t.n2, w, null, true);
            t.n3 = direct_1.createDiv();
            direct_1.setStyle(t.n3, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n3, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n3, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n3, 11 /*padding*/, staticObj[3]);
            t.n4 = direct_1.createDiv();
            direct_1.setStyle(t.n4, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n4, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n4, 1 /*height*/, staticObj[5]);
            t.n5 = direct_1.createDiv();
            direct_1.setStyle(t.n5, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n5, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n5, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n5, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n5, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n5, 66 /*overflow*/, true);
            direct_1.setStyle(t.n5, 58 /*transform*/, staticObj[7]);
            t.n6 = direct_1.createDiv();
            direct_1.setStyle(t.n6, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n6, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n6, 1 /*height*/, staticObj[5]);
            t.n7 = direct_1.createDiv();
            direct_1.setStyle(t.n7, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n7, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n7, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n7, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n7, 66 /*overflow*/, true);
            direct_1.setStyle(t.n7, 20 /*marginLeft*/, staticObj[6]);
            t.n8 = direct_1.createDiv();
            direct_1.setStyle(t.n8, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n8, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n8, 1 /*height*/, staticObj[5]);
            t.n9 = direct_1.createDiv();
            direct_1.setStyle(t.n9, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n9, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n9, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n9, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n9, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n9, 66 /*overflow*/, true);
            direct_1.setStyle(t.n9, 58 /*transform*/, staticObj[7]);
            t.n10 = direct_1.createDiv();
            direct_1.setStyle(t.n10, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n10, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n10, 1 /*height*/, staticObj[5]);
            t.n11 = direct_1.createDiv();
            direct_1.setStyle(t.n11, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n11, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n11, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n11, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n11, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n11, 66 /*overflow*/, true);
            direct_1.setStyle(t.n11, 58 /*transform*/, staticObj[7]);
            t.n12 = direct_1.createDiv();
            direct_1.setStyle(t.n12, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n12, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n12, 1 /*height*/, staticObj[5]);
            t.n13 = direct_1.createDiv();
            direct_1.setStyle(t.n13, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n13, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n13, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n13, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n13, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n13, 66 /*overflow*/, true);
            direct_1.setStyle(t.n13, 58 /*transform*/, staticObj[7]);
            t.n14 = direct_1.createDiv();
            direct_1.setStyle(t.n14, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n14, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n14, 1 /*height*/, staticObj[5]);
            t.n15 = direct_1.createDiv();
            direct_1.setStyle(t.n15, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n15, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n15, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n15, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n15, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n15, 66 /*overflow*/, true);
            direct_1.setStyle(t.n15, 58 /*transform*/, staticObj[7]);
            t.n16 = direct_1.createDiv();
            direct_1.setStyle(t.n16, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n16, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n16, 1 /*height*/, staticObj[5]);
            t.n17 = direct_1.createDiv();
            direct_1.setStyle(t.n17, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n17, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n17, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n17, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n17, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n17, 66 /*overflow*/, true);
            direct_1.setStyle(t.n17, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n17, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n18 = direct_1.createDiv();
            direct_1.setStyle(t.n18, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n18, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n18, 1 /*height*/, staticObj[5]);
            t.n19 = direct_1.createDiv();
            direct_1.setStyle(t.n19, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n19, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n19, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n19, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n19, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n19, 66 /*overflow*/, true);
            direct_1.setStyle(t.n19, 58 /*transform*/, staticObj[7]);
            t.n20 = direct_1.createDiv();
            direct_1.setStyle(t.n20, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n20, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n20, 1 /*height*/, staticObj[5]);
            t.n21 = direct_1.createDiv();
            direct_1.setStyle(t.n21, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n21, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n21, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n21, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n21, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n21, 66 /*overflow*/, true);
            direct_1.setStyle(t.n21, 58 /*transform*/, staticObj[7]);
            t.n22 = direct_1.createDiv();
            direct_1.setStyle(t.n22, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n22, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n22, 1 /*height*/, staticObj[5]);
            t.n23 = direct_1.createDiv();
            direct_1.setStyle(t.n23, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n23, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n23, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n23, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n23, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n23, 66 /*overflow*/, true);
            direct_1.setStyle(t.n23, 58 /*transform*/, staticObj[7]);
            t.n24 = direct_1.createDiv();
            direct_1.setStyle(t.n24, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n24, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n24, 1 /*height*/, staticObj[5]);
            t.n25 = direct_1.createDiv();
            direct_1.setStyle(t.n25, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n25, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n25, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n25, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n25, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n25, 66 /*overflow*/, true);
            direct_1.setStyle(t.n25, 58 /*transform*/, staticObj[7]);
            t.n26 = direct_1.createDiv();
            direct_1.setStyle(t.n26, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n26, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n26, 1 /*height*/, staticObj[5]);
            t.n27 = direct_1.createDiv();
            direct_1.setStyle(t.n27, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n27, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n27, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n27, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n27, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n27, 66 /*overflow*/, true);
            direct_1.setStyle(t.n27, 58 /*transform*/, staticObj[7]);
            t.n28 = direct_1.createDiv();
            direct_1.setStyle(t.n28, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n28, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n28, 1 /*height*/, staticObj[5]);
            t.n29 = direct_1.createDiv();
            direct_1.setStyle(t.n29, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n29, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n29, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n29, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n29, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n29, 66 /*overflow*/, true);
            direct_1.setStyle(t.n29, 58 /*transform*/, staticObj[7]);
            t.n30 = direct_1.createDiv();
            direct_1.setStyle(t.n30, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n30, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n30, 1 /*height*/, staticObj[5]);
            t.n31 = direct_1.createDiv();
            direct_1.setStyle(t.n31, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n31, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n31, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n31, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n31, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n31, 66 /*overflow*/, true);
            direct_1.setStyle(t.n31, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n31, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n32 = direct_1.createDiv();
            direct_1.setStyle(t.n32, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n32, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n32, 1 /*height*/, staticObj[5]);
            t.n33 = direct_1.createDiv();
            direct_1.setStyle(t.n33, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n33, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n33, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n33, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n33, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n33, 66 /*overflow*/, true);
            direct_1.setStyle(t.n33, 58 /*transform*/, staticObj[7]);
            t.n34 = direct_1.createDiv();
            direct_1.setStyle(t.n34, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n34, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n34, 1 /*height*/, staticObj[5]);
            t.n35 = direct_1.createDiv();
            direct_1.setStyle(t.n35, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n35, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n35, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n35, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n35, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n35, 66 /*overflow*/, true);
            direct_1.setStyle(t.n35, 58 /*transform*/, staticObj[7]);
            t.n36 = direct_1.createDiv();
            direct_1.setStyle(t.n36, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n36, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n36, 1 /*height*/, staticObj[5]);
            t.n37 = direct_1.createDiv();
            direct_1.setStyle(t.n37, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n37, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n37, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n37, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n37, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n37, 66 /*overflow*/, true);
            direct_1.setStyle(t.n37, 58 /*transform*/, staticObj[7]);
            t.n38 = direct_1.createDiv();
            direct_1.setStyle(t.n38, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n38, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n38, 1 /*height*/, staticObj[5]);
            t.n39 = direct_1.createDiv();
            direct_1.setStyle(t.n39, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n39, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n39, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n39, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n39, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n39, 66 /*overflow*/, true);
            direct_1.setStyle(t.n39, 58 /*transform*/, staticObj[7]);
            t.n40 = direct_1.createDiv();
            direct_1.setStyle(t.n40, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n40, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n40, 1 /*height*/, staticObj[5]);
            t.n41 = direct_1.createDiv();
            direct_1.setStyle(t.n41, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n41, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n41, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n41, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n41, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n41, 66 /*overflow*/, true);
            direct_1.setStyle(t.n41, 58 /*transform*/, staticObj[7]);
            t.n42 = direct_1.createDiv();
            direct_1.setStyle(t.n42, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n42, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n42, 1 /*height*/, staticObj[5]);
            t.n43 = direct_1.createDiv();
            direct_1.setStyle(t.n43, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n43, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n43, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n43, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n43, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n43, 66 /*overflow*/, true);
            direct_1.setStyle(t.n43, 58 /*transform*/, staticObj[7]);
            t.n44 = direct_1.createDiv();
            direct_1.setStyle(t.n44, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n44, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n44, 1 /*height*/, staticObj[5]);
            t.n45 = direct_1.createDiv();
            direct_1.setStyle(t.n45, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n45, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n45, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n45, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n45, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n45, 66 /*overflow*/, true);
            direct_1.setStyle(t.n45, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n45, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n46 = direct_1.createDiv();
            direct_1.setStyle(t.n46, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n46, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n46, 1 /*height*/, staticObj[5]);
            t.n47 = direct_1.createDiv();
            direct_1.setStyle(t.n47, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n47, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n47, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n47, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n47, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n47, 66 /*overflow*/, true);
            direct_1.setStyle(t.n47, 58 /*transform*/, staticObj[7]);
            t.n48 = direct_1.createDiv();
            direct_1.setStyle(t.n48, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n48, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n48, 1 /*height*/, staticObj[5]);
            t.n49 = direct_1.createDiv();
            direct_1.setStyle(t.n49, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n49, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n49, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n49, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n49, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n49, 66 /*overflow*/, true);
            direct_1.setStyle(t.n49, 58 /*transform*/, staticObj[7]);
            t.n50 = direct_1.createDiv();
            direct_1.setStyle(t.n50, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n50, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n50, 1 /*height*/, staticObj[5]);
            t.n51 = direct_1.createDiv();
            direct_1.setStyle(t.n51, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n51, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n51, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n51, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n51, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n51, 66 /*overflow*/, true);
            direct_1.setStyle(t.n51, 58 /*transform*/, staticObj[7]);
            t.n52 = direct_1.createDiv();
            direct_1.setStyle(t.n52, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n52, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n52, 1 /*height*/, staticObj[5]);
            t.n53 = direct_1.createDiv();
            direct_1.setStyle(t.n53, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n53, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n53, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n53, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n53, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n53, 66 /*overflow*/, true);
            direct_1.setStyle(t.n53, 58 /*transform*/, staticObj[7]);
            t.n54 = direct_1.createDiv();
            direct_1.setStyle(t.n54, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n54, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n54, 1 /*height*/, staticObj[5]);
            t.n55 = direct_1.createDiv();
            direct_1.setStyle(t.n55, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n55, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n55, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n55, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n55, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n55, 66 /*overflow*/, true);
            direct_1.setStyle(t.n55, 58 /*transform*/, staticObj[7]);
            t.n56 = direct_1.createDiv();
            direct_1.setStyle(t.n56, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n56, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n56, 1 /*height*/, staticObj[5]);
            t.n57 = direct_1.createDiv();
            direct_1.setStyle(t.n57, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n57, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n57, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n57, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n57, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n57, 66 /*overflow*/, true);
            direct_1.setStyle(t.n57, 58 /*transform*/, staticObj[7]);
            t.n58 = direct_1.createDiv();
            direct_1.setStyle(t.n58, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n58, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n58, 1 /*height*/, staticObj[5]);
            t.n59 = direct_1.createDiv();
            direct_1.setStyle(t.n59, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n59, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n59, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n59, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n59, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n59, 66 /*overflow*/, true);
            direct_1.setStyle(t.n59, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n59, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n60 = direct_1.createWidget(imgmap_vue_1.default, w, {
                attrs: {
                    name: w.a_02
                },
                style: {
                    backgroundColor /*backgroundColor*/: "#ff0000",
                    width /*width*/: "70px",
                    height /*height*/: "70px",
                    position /*position*/: "absolute",
                    transform /*transform*/: "rotateZ(-45deg)"
                }
            });
            t.n61 = direct_1.createDiv();
            direct_1.setStyle(t.n61, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n61, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n61, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n61, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n61, 66 /*overflow*/, true);
            direct_1.setStyle(t.n61, 20 /*marginLeft*/, staticObj[6]);
            t.n62 = direct_1.createDiv();
            direct_1.setStyle(t.n62, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n62, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n62, 1 /*height*/, staticObj[5]);
            t.n63 = direct_1.createDiv();
            direct_1.setStyle(t.n63, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n63, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n63, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n63, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n63, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n63, 66 /*overflow*/, true);
            direct_1.setStyle(t.n63, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n63, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n64 = direct_1.createDiv();
            direct_1.setStyle(t.n64, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n64, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n64, 1 /*height*/, staticObj[5]);
            t.n65 = direct_1.createDiv();
            direct_1.setStyle(t.n65, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n65, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n65, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n65, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n65, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n65, 66 /*overflow*/, true);
            direct_1.setStyle(t.n65, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n65, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n66 = direct_1.createDiv();
            direct_1.setStyle(t.n66, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n66, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n66, 1 /*height*/, staticObj[5]);
            t.n67 = direct_1.createDiv();
            direct_1.setStyle(t.n67, 46 /*backgroundColor*/, staticObj[1]);
            direct_1.setStyle(t.n67, 0 /*width*/, staticObj[2]);
            direct_1.setStyle(t.n67, 1 /*height*/, staticObj[2]);
            direct_1.setStyle(t.n67, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n67, 11 /*padding*/, staticObj[3]);
            direct_1.setStyle(t.n67, 66 /*overflow*/, true);
            direct_1.setStyle(t.n67, 58 /*transform*/, staticObj[7]);
            direct_1.setEvent(t.n67, "pointerclick", $event => {
                let r = w.change($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            t.n68 = direct_1.createDiv();
            direct_1.setStyle(t.n68, 46 /*backgroundColor*/, staticObj[4]);
            direct_1.setStyle(t.n68, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n68, 1 /*height*/, staticObj[5]);
            return this.n2;
        }
        d() {
            let t = this;
            direct_1.destroyContext(t.n60);
        }
        m(target, anchor) {
            let t = this,
                w = t.w;
            direct_1.append(t.n4, t.n3);
            direct_1.append(t.n3, t.n2);
            direct_1.append(t.n6, t.n5);
            direct_1.append(t.n5, t.n2);
            direct_1.append(t.n8, t.n7);
            direct_1.append(t.n7, t.n2);
            direct_1.append(t.n10, t.n9);
            direct_1.append(t.n9, t.n2);
            direct_1.append(t.n12, t.n11);
            direct_1.append(t.n11, t.n2);
            direct_1.append(t.n14, t.n13);
            direct_1.append(t.n13, t.n2);
            direct_1.append(t.n16, t.n15);
            direct_1.append(t.n15, t.n2);
            direct_1.append(t.n18, t.n17);
            direct_1.append(t.n17, t.n2);
            direct_1.append(t.n20, t.n19);
            direct_1.append(t.n19, t.n2);
            direct_1.append(t.n22, t.n21);
            direct_1.append(t.n21, t.n2);
            direct_1.append(t.n24, t.n23);
            direct_1.append(t.n23, t.n2);
            direct_1.append(t.n26, t.n25);
            direct_1.append(t.n25, t.n2);
            direct_1.append(t.n28, t.n27);
            direct_1.append(t.n27, t.n2);
            direct_1.append(t.n30, t.n29);
            direct_1.append(t.n29, t.n2);
            direct_1.append(t.n32, t.n31);
            direct_1.append(t.n31, t.n2);
            direct_1.append(t.n34, t.n33);
            direct_1.append(t.n33, t.n2);
            direct_1.append(t.n36, t.n35);
            direct_1.append(t.n35, t.n2);
            direct_1.append(t.n38, t.n37);
            direct_1.append(t.n37, t.n2);
            direct_1.append(t.n40, t.n39);
            direct_1.append(t.n39, t.n2);
            direct_1.append(t.n42, t.n41);
            direct_1.append(t.n41, t.n2);
            direct_1.append(t.n44, t.n43);
            direct_1.append(t.n43, t.n2);
            direct_1.append(t.n46, t.n45);
            direct_1.append(t.n45, t.n2);
            direct_1.append(t.n48, t.n47);
            direct_1.append(t.n47, t.n2);
            direct_1.append(t.n50, t.n49);
            direct_1.append(t.n49, t.n2);
            direct_1.append(t.n52, t.n51);
            direct_1.append(t.n51, t.n2);
            direct_1.append(t.n54, t.n53);
            direct_1.append(t.n53, t.n2);
            direct_1.append(t.n56, t.n55);
            direct_1.append(t.n55, t.n2);
            direct_1.append(t.n58, t.n57);
            direct_1.append(t.n57, t.n2);
            direct_1.mountChildWidget(t.n60, t.n59);
            direct_1.append(t.n59, t.n2);
            direct_1.append(t.n62, t.n61);
            direct_1.append(t.n61, t.n2);
            direct_1.append(t.n64, t.n63);
            direct_1.append(t.n63, t.n2);
            direct_1.append(t.n66, t.n65);
            direct_1.append(t.n65, t.n2);
            direct_1.append(t.n68, t.n67);
            direct_1.append(t.n67, t.n2);
            direct_1.insertBefore(t.n2, target, anchor);
        }
        p() {
            let t = this,
                w = t.w;
            let { dirty0 } = w._$info;
            direct_1.extendAttr(t.n2, w);
            var _$wAttrs = {};
            if (dirty0 & 1) {
                const _$attrs = {};
                if (dirty0 & 1) _$attrs.name = w.a_02;
                _$wAttrs.attrs = _$attrs;
            }
            ;
            direct_1.patchAttrsForWidget(t.n60, _$wAttrs);
            return this.n2;
        }
    }
    exports.BW2 = BW2;
});