_$pi.define("app_c/demo/ui/show/base/filter.vue.tpl", ["require", "exports", "module", "pi_gui/widget/direct"], function (require, exports, module, direct_1) {
    "use strict";

    exports.BW2 = void 0;
    const staticObj = [[1, 1], [0, 200], [0.2, 0.2, 0.35, 1], [0, 64], [1, 1, 1, 1], [0, 120], [0, 10], [0, 20], [0.5, 0.5, 0.5, 1], [0, 50]];
    class BW2 {
        constructor(widget, ctx) {
            this.w = widget;
        }
        c() {
            let t = this,
                w = t.w;
            t.n2 = direct_1.createDiv();
            direct_1.setStyle(t.n2, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n2, 1 /*height*/, staticObj[0]);
            direct_1.setStyle(t.n2, 22 /*flexWrap*/, 1);
            direct_1.extendAttr(t.n2, w, null, true);
            t.n3 = direct_1.createDiv();
            direct_1.setStyle(t.n3, 0 /*width*/, staticObj[0]);
            t.n4 = direct_1.createDiv();
            direct_1.setStyle(t.n4, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n4, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n4, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setStyle(t.n4, 68 /*filter*/, 'hsi(' + w.h + ',' + w.s + ',' + w.i + ')');
            t.n5 = direct_1.createImg();
            direct_1.setAttr(t.n5, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n5, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n5, 1 /*height*/, staticObj[3]);
            t.n6 = direct_1.createDiv();
            t.n7 = direct_1.createSpan();
            direct_1.setStyle(t.n7, 30 /*color*/, staticObj[4]);
            direct_1.setStyle(t.n7, 0 /*width*/, staticObj[5]);
            direct_1.setStyle(t.n7, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n7, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n7, 42 /*fontSize*/, 20);
            direct_1.setText(t.n7, "hsi:" + w.h + "," + w.s + "," + w.i);
            t.n8 = direct_1.createSpan();
            direct_1.setStyle(t.n8, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n8, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n8, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n8, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n8, "pointerclick", $event => {
                let r = w.changeh($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n8, "h+10");
            t.n9 = direct_1.createSpan();
            direct_1.setStyle(t.n9, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n9, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n9, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n9, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n9, "pointerclick", $event => {
                let r = w.changes($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n9, "s+10");
            t.n10 = direct_1.createSpan();
            direct_1.setStyle(t.n10, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n10, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n10, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n10, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n10, "pointerclick", $event => {
                let r = w.changei($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n10, "i+10");
            t.n11 = direct_1.createDiv();
            direct_1.setStyle(t.n11, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n11, 22 /*flexWrap*/, 1);
            direct_1.setStyle(t.n11, 7 /*top*/, staticObj[9]);
            t.n12 = direct_1.createDiv();
            direct_1.setStyle(t.n12, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n12, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n12, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setStyle(t.n12, 68 /*filter*/, 'hue-rotate(' + w.hueRotate + 'deg)' + ' saturate(' + w.saturate + '%)' + ' brightness(' + w.brightness + '%)');
            t.n13 = direct_1.createImg();
            direct_1.setAttr(t.n13, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n13, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n13, 1 /*height*/, staticObj[3]);
            t.n14 = direct_1.createDiv();
            direct_1.setStyle(t.n14, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n14, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n14, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setStyle(t.n14, 68 /*filter*/, 'grayscale(' + w.grayscale + '%)');
            t.n15 = direct_1.createImg();
            direct_1.setAttr(t.n15, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n15, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n15, 1 /*height*/, staticObj[3]);
            t.n16 = direct_1.createSpan();
            direct_1.setStyle(t.n16, 30 /*color*/, staticObj[4]);
            direct_1.setStyle(t.n16, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n16, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n16, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n16, 42 /*fontSize*/, 16);
            direct_1.setText(t.n16, "hueRotate:" + w.hueRotate + "deg,saturate:" + w.saturate + "%,brightness:" + w.brightness + "%,grayscale:" + w.grayscale + "%");
            t.n17 = direct_1.createDiv();
            direct_1.setStyle(t.n17, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n17, 22 /*flexWrap*/, 1);
            t.n18 = direct_1.createSpan();
            direct_1.setStyle(t.n18, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n18, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n18, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n18, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n18, "pointerclick", $event => {
                let r = w.changeh1($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n18, "色相+10");
            t.n19 = direct_1.createSpan();
            direct_1.setStyle(t.n19, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n19, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n19, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n19, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n19, "pointerclick", $event => {
                let r = w.changes1($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n19, "饱和度+10");
            t.n20 = direct_1.createSpan();
            direct_1.setStyle(t.n20, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n20, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n20, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n20, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n20, "pointerclick", $event => {
                let r = w.changei1($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n20, "亮度+10");
            t.n21 = direct_1.createSpan();
            direct_1.setStyle(t.n21, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n21, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n21, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n21, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n21, "pointerclick", $event => {
                let r = w.changeg1($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n21, "变灰+10");
            t.n22 = direct_1.createDiv();
            direct_1.setStyle(t.n22, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n22, 22 /*flexWrap*/, 1);
            direct_1.setStyle(t.n22, 7 /*top*/, staticObj[9]);
            t.n23 = direct_1.createDiv();
            direct_1.setStyle(t.n23, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n23, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n23, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setClass(t.n23, direct_1.classHash(w.cssList[w.cssListi], w));
            t.n24 = direct_1.createImg();
            direct_1.setAttr(t.n24, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n24, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n24, 1 /*height*/, staticObj[3]);
            t.n25 = direct_1.createSpan();
            direct_1.setStyle(t.n25, 30 /*color*/, staticObj[4]);
            direct_1.setStyle(t.n25, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n25, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n25, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n25, 42 /*fontSize*/, 16);
            direct_1.setText(t.n25, "cssName:" + w.cssList[w.cssListi]);
            t.n26 = direct_1.createSpan();
            direct_1.setStyle(t.n26, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n26, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n26, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n26, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n26, "pointerclick", $event => {
                let r = w.changegcss($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n26, "修改class");
            t.n27 = direct_1.createDiv();
            direct_1.setStyle(t.n27, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n27, 22 /*flexWrap*/, 1);
            direct_1.setStyle(t.n27, 7 /*top*/, staticObj[9]);
            t.n28 = direct_1.createDiv();
            direct_1.setStyle(t.n28, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n28, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n28, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setStyle(t.n28, 68 /*filter*/, 'blur(' + w.blur + 'px)');
            t.n29 = direct_1.createImg();
            direct_1.setAttr(t.n29, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n29, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n29, 1 /*height*/, staticObj[3]);
            t.n30 = direct_1.createImg();
            direct_1.setAttr(t.n30, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n30, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n30, 1 /*height*/, staticObj[3]);
            t.n31 = direct_1.createImg();
            direct_1.setAttr(t.n31, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n31, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n31, 1 /*height*/, staticObj[3]);
            t.n32 = direct_1.createImg();
            direct_1.setAttr(t.n32, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n32, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n32, 1 /*height*/, staticObj[3]);
            t.n33 = direct_1.createSpan();
            direct_1.setStyle(t.n33, 30 /*color*/, staticObj[4]);
            direct_1.setStyle(t.n33, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n33, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n33, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n33, 42 /*fontSize*/, 16);
            direct_1.setText(t.n33, "blur:" + w.blur + "px");
            t.n34 = direct_1.createDiv();
            direct_1.setStyle(t.n34, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n34, 22 /*flexWrap*/, 1);
            t.n35 = direct_1.createSpan();
            direct_1.setStyle(t.n35, 46 /*backgroundColor*/, staticObj[8]);
            direct_1.setStyle(t.n35, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n35, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n35, 42 /*fontSize*/, 20);
            direct_1.setEvent(t.n35, "pointerclick", $event => {
                let r = w.changeBlur($event);
                $event && typeof $event === "object" && ($event.stopPropagation = !r);
                return r;
            });
            direct_1.setText(t.n35, "改变blur半径");
            t.n36 = direct_1.createDiv();
            direct_1.setStyle(t.n36, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n36, 22 /*flexWrap*/, 1);
            direct_1.setStyle(t.n36, 7 /*top*/, staticObj[9]);
            t.n37 = direct_1.createDiv();
            direct_1.setStyle(t.n37, 0 /*width*/, staticObj[1]);
            direct_1.setStyle(t.n37, 1 /*height*/, staticObj[1]);
            direct_1.setStyle(t.n37, 46 /*backgroundColor*/, staticObj[2]);
            direct_1.setClass(t.n37, 858111538);
            t.n38 = direct_1.createImg();
            direct_1.setAttr(t.n38, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n38, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n38, 1 /*height*/, staticObj[3]);
            t.n39 = direct_1.createImg();
            direct_1.setAttr(t.n39, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n39, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n39, 1 /*height*/, staticObj[3]);
            t.n40 = direct_1.createImg();
            direct_1.setAttr(t.n40, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n40, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n40, 1 /*height*/, staticObj[3]);
            t.n41 = direct_1.createImg();
            direct_1.setAttr(t.n41, "src", "app_c/demo/ui/images/act_04.png");
            direct_1.setStyle(t.n41, 0 /*width*/, staticObj[3]);
            direct_1.setStyle(t.n41, 1 /*height*/, staticObj[3]);
            t.n42 = direct_1.createSpan();
            direct_1.setStyle(t.n42, 30 /*color*/, staticObj[4]);
            direct_1.setStyle(t.n42, 0 /*width*/, staticObj[0]);
            direct_1.setStyle(t.n42, 20 /*marginLeft*/, staticObj[6]);
            direct_1.setStyle(t.n42, 1 /*height*/, staticObj[7]);
            direct_1.setStyle(t.n42, 42 /*fontSize*/, 16);
            direct_1.setText(t.n42, "测试在class中声明blur");
            return this.n2;
        }
        m(target, anchor) {
            let t = this,
                w = t.w;
            direct_1.append(t.n5, t.n4);
            direct_1.append(t.n4, t.n3);
            direct_1.append(t.n7, t.n6);
            direct_1.append(t.n8, t.n6);
            direct_1.append(t.n9, t.n6);
            direct_1.append(t.n10, t.n6);
            direct_1.append(t.n6, t.n3);
            direct_1.append(t.n3, t.n2);
            direct_1.append(t.n13, t.n12);
            direct_1.append(t.n12, t.n11);
            direct_1.append(t.n15, t.n14);
            direct_1.append(t.n14, t.n11);
            direct_1.append(t.n16, t.n11);
            direct_1.append(t.n18, t.n17);
            direct_1.append(t.n19, t.n17);
            direct_1.append(t.n20, t.n17);
            direct_1.append(t.n21, t.n17);
            direct_1.append(t.n17, t.n11);
            direct_1.append(t.n11, t.n2);
            direct_1.append(t.n24, t.n23);
            direct_1.append(t.n23, t.n22);
            direct_1.append(t.n25, t.n22);
            direct_1.append(t.n26, t.n22);
            direct_1.append(t.n22, t.n2);
            direct_1.append(t.n29, t.n28);
            direct_1.append(t.n30, t.n28);
            direct_1.append(t.n31, t.n28);
            direct_1.append(t.n32, t.n28);
            direct_1.append(t.n28, t.n27);
            direct_1.append(t.n33, t.n27);
            direct_1.append(t.n35, t.n34);
            direct_1.append(t.n34, t.n27);
            direct_1.append(t.n27, t.n2);
            direct_1.append(t.n38, t.n37);
            direct_1.append(t.n39, t.n37);
            direct_1.append(t.n40, t.n37);
            direct_1.append(t.n41, t.n37);
            direct_1.append(t.n37, t.n36);
            direct_1.append(t.n42, t.n36);
            direct_1.append(t.n36, t.n2);
            direct_1.insertBefore(t.n2, target, anchor);
        }
        p() {
            let t = this,
                w = t.w;
            let { dirty0 } = w._$info;
            direct_1.extendAttr(t.n2, w);
            if (dirty0 & 7) direct_1.setStyle(t.n4, 68 /*filter*/, 'hsi(' + w.h + ',' + w.s + ',' + w.i + ')');
            if (dirty0 & 7) direct_1.setText(t.n7, "hsi:" + w.h + "," + w.s + "," + w.i);
            if (dirty0 & 56) direct_1.setStyle(t.n12, 68 /*filter*/, 'hue-rotate(' + w.hueRotate + 'deg)' + ' saturate(' + w.saturate + '%)' + ' brightness(' + w.brightness + '%)');
            if (dirty0 & 64) direct_1.setStyle(t.n14, 68 /*filter*/, 'grayscale(' + w.grayscale + '%)');
            if (dirty0 & 120) direct_1.setText(t.n16, "hueRotate:" + w.hueRotate + "deg,saturate:" + w.saturate + "%,brightness:" + w.brightness + "%,grayscale:" + w.grayscale + "%");
            if (dirty0 & 384) direct_1.setClass(t.n23, direct_1.classHash(w.cssList[w.cssListi], w));
            if (dirty0 & 384) direct_1.setText(t.n25, "cssName:" + w.cssList[w.cssListi]);
            if (dirty0 & 512) direct_1.setStyle(t.n28, 68 /*filter*/, 'blur(' + w.blur + 'px)');
            if (dirty0 & 512) direct_1.setText(t.n33, "blur:" + w.blur + "px");
            return this.n2;
        }
    }
    exports.BW2 = BW2;
});