[package]
name = "ui_render_exports_macro"
version = "0.2.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[dependencies]
paste = "0.1"

[features]
default = ["pi_js_export", "wasm_bindgen"]
pi_js_export = []
wasm_bindgen = []

